# Custom PostgreSQL with pgTAP for database testing
FROM postgres:16-alpine

# Install build dependencies, compile pgTAP, clean up
RUN apk add --no-cache --virtual .build-deps \
        make \
        perl \
        git \
    && git clone --depth 1 https://github.com/theory/pgtap.git /tmp/pgtap \
    && cd /tmp/pgtap \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/pgtap \
    && apk del .build-deps
