-- 000116_sovereignty_reports.up.sql
--
-- Backing store for the public CLOUD Act Exposure Checker
-- (Tool 1 of the growth spec, issue #548). Two tables:
--
--   * `sovereignty_reports` — one row per completed check. Hash-
--     addressable so /r/{hash} permalinks stay stable, and stores
--     the exact set of vendor slugs the user picked plus the
--     computed score. IP + user_agent kept for spam correlation,
--     UTM/campaign metadata for attribution.
--
--   * `sovereignty_leads` — email captures gated behind the PDF
--     download. Segmented by role + data-sensitivity so the drip
--     sequence can branch (dev/founder vs agency/dpo).
--
-- Grants follow the #443-class REVOKE-then-GRANT pattern:
--   * Gateway pool gets INSERT on reports (the public POST /report
--     endpoint runs there — anonymous, IP-rate-limited). NO SELECT
--     on either table — the historic ledger, emails, and campaign
--     data are all developer-pool-only.
--   * Leads never touch the gateway pool at all.
--
-- No explicit BEGIN/COMMIT: golang-migrate wraps each .up.sql tx.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE public.sovereignty_reports (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- URL-safe short hash. Generated by the handler
    -- (crockford-base32, 10 chars, ~50 bits of entropy — enough for
    -- the /r/{hash} link, small enough to be shareable). UNIQUE so
    -- collisions surface as a retry, not a silent overwrite.
    hash              TEXT NOT NULL UNIQUE,
    -- The vendor slugs the user picked, in the order they were
    -- selected. Deliberately JSONB rather than a normalized join
    -- table: the vendor set is small (typically ≤20), the row is
    -- immutable once written, and read paths always need the full
    -- set. Also lets the schema evolve without a migration if the
    -- checker later stores per-slug metadata (e.g. severity per
    -- vendor) alongside the picks.
    vendor_slugs      JSONB NOT NULL,
    -- Optional severity modifier: health / legal / financial /
    -- children. Tightens thresholds in the scoring function.
    -- NULL = "standard" (no tightening).
    severity_modifier TEXT NULL,
    -- The computed score envelope: {overall, red_count, amber_count,
    -- green_count, exposure_percent, by_dimension}. Persisted so
    -- re-renders (OG image, PDF) don't need to re-run the scoring
    -- function against a potentially-changed vendor DB.
    computed_score    JSONB NOT NULL,
    -- Attribution metadata: {referrer, utm_source, utm_campaign,
    -- utm_medium, client_lang}. Everything the frontend can capture
    -- without a login. Optional per-field.
    campaign_metadata JSONB NULL,
    -- Spam-correlation fingerprints (same shape as contact_requests
    -- and support_requests).
    ip_address        INET NULL,
    user_agent        TEXT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Field bounds:
    CHECK (char_length(hash) BETWEEN 8 AND 32),
    CHECK (severity_modifier IS NULL
           OR severity_modifier IN ('health', 'legal', 'financial', 'children'))
);

CREATE INDEX ix_sovereignty_reports_hash    ON public.sovereignty_reports (hash);
CREATE INDEX ix_sovereignty_reports_created ON public.sovereignty_reports (created_at DESC);

CREATE TABLE public.sovereignty_leads (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- CITEXT for case-insensitive dedup — a user typing
    -- "Alice@Example.com" and later "alice@example.com" hits the
    -- same row. UNIQUE per campaign so the same email can appear
    -- in more than one funnel over time.
    email           CITEXT NOT NULL,
    role            TEXT NULL,
    sensitivity     TEXT NULL,
    -- Optional link back to the report that triggered the PDF
    -- download. SET NULL on source-report delete so a GDPR-erasure
    -- of the report doesn't cascade the lead away.
    source_hash     TEXT NULL REFERENCES public.sovereignty_reports(hash) ON DELETE SET NULL,
    sequence_stage  INT NOT NULL DEFAULT 0,
    -- Namespaced so a future "DPA generator" (Tool 2) can share
    -- the same leads table.
    campaign        TEXT NOT NULL DEFAULT 'sovereignty_check',
    unsubscribed_at TIMESTAMPTZ NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (email, campaign),

    CHECK (role IS NULL OR role IN ('dev', 'founder', 'agency', 'dpo', 'procurement')),
    CHECK (sensitivity IS NULL
           OR sensitivity IN ('health', 'legal', 'financial', 'children', 'standard')),
    CHECK (sequence_stage >= 0 AND sequence_stage <= 10),
    CHECK (char_length(campaign) BETWEEN 1 AND 64)
);

-- Only-open-leads index — the drip worker scans this on every
-- tick, so keep it tiny.
CREATE INDEX ix_sovereignty_leads_stage
    ON public.sovereignty_leads (campaign, sequence_stage)
    WHERE unsubscribed_at IS NULL;

-- ── Grants ─────────────────────────────────────────────────────
-- Same #443-class pitfall as contact_requests / organizations /
-- support_requests: migration 000037 ALTER DEFAULT PRIVILEGES
-- auto-grants the gateway pool full DML on every new
-- migrator-owned public.* table. Reports carry IPs + user-agents;
-- leads carry emails. All PII. REVOKE first, GRANT narrow.
REVOKE ALL ON public.sovereignty_reports FROM eurobase_gateway;
REVOKE ALL ON public.sovereignty_leads   FROM eurobase_gateway;
-- Gateway needs INSERT on reports (public POST endpoint) but
-- MUST NOT read historical rows. Leads never touch gateway.
GRANT INSERT ON public.sovereignty_reports TO eurobase_gateway;
GRANT SELECT, INSERT, UPDATE ON public.sovereignty_reports TO eurobase_developer;
GRANT SELECT, INSERT, UPDATE ON public.sovereignty_leads   TO eurobase_developer;

COMMENT ON TABLE public.sovereignty_reports IS
  'Public CLOUD Act Exposure Checker reports. One row per completed check. Hash-addressable for /r/{hash} permalinks. Insert via anonymous POST /platform/public/sovereignty/report; read via developer pool only.';
COMMENT ON COLUMN public.sovereignty_reports.hash IS
  '10-char URL-safe short hash (crockford-base32). ~50 bits of entropy. UNIQUE — the handler retries on collision.';
COMMENT ON COLUMN public.sovereignty_reports.computed_score IS
  'Score envelope: {overall, red_count, amber_count, green_count, exposure_percent, by_dimension}. Persisted so re-renders (OG image, PDF) do not need to re-run the scoring function against a changed vendor DB.';
COMMENT ON TABLE public.sovereignty_leads IS
  'Email captures from the PDF gate. Namespaced by campaign so future lead-magnet tools share the table.';
